# Generated by Django 3.2.9 on 2021-11-19 11:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mainapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Имя должно содержать от 3 до 20 символов'), django.core.validators.MaxLengthValidator(limit_value=20, message='Имя должно содержать от 3 до 20 символов')], verbose_name='Имя мастера')),
                ('photo', models.ImageField(upload_to='masters', verbose_name='Фото мастера')),
                ('description', models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(limit_value=1000, message='Информация должна содержать не более 1000 символов')], verbose_name='Информация про мастера')),
            ],
            options={
                'verbose_name': 'мастер',
                'verbose_name_plural': 'мастера',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='Название услуги должно содержать от 5 до 50 символов'), django.core.validators.MaxLengthValidator(limit_value=50, message='Название услуги должно содержать от 5 до 50 символов')], verbose_name='Название услуги')),
                ('photo', models.ImageField(upload_to='service', verbose_name='Фото')),
                ('nums_minutes_to_complete', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=5, message='Продолжительность не может быть меньше 5 минут'), django.core.validators.MaxValueValidator(limit_value=180, message='Продолжительность не может быть более 180 минут')], verbose_name='Продолжительность в минутах')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(limit_value=5, message='Стоимость услуги должна быть от 5 до 1000 BYN'), django.core.validators.MaxValueValidator(limit_value=1000, message='Стоимость услуги должна быть от 5 до 1000 BYN')])),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(validators=[mainapp.validators.date_greater_than_present_validator], verbose_name='Дата и время записи')),
                ('end_time', models.DateTimeField()),
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mainapp.master', verbose_name='Мастер')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mainapp.service', verbose_name='Услуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
            },
        ),
    ]
